In a Hurry
140

xooo
oooo
oooo
oooo

oooo
oooo
oooo
oooo

ooox
oooo
oooo
oooo

oooo
oooo
oooo
oooo

xooo
oooo
oooo
oooo

oooo
oooo
oooo
oooo

ooox
oooo
oooo
oooo

oooo
oooo
oooo
oooo

oxxo
oooo
oooo
oooo

oooo
oooo
oooo
oooo

xoox
oooo
oooo
oooo

oooo
oooo
oooo
oooo

xooo
oooo
oooo
oooo

oooo
oooo
oooo
oooo

ooox
oooo
oooo
oooo

oooo
oooo
oooo
oooo

xooo
oooo
oooo
oooo

oooo
oooo
oooo
oooo

xoox
oooo
oooo
oooo

oooo
oooo
oooo
oooo

xooo
oooo
oooo
oooo

oooo
oooo
oooo
oooo

xoox
oooo
oooo
oooo

oooo
oooo
oooo
oooo

oxxo
oooo
oooo
oooo

oooo
oooo
oooo
oooo

xoox
oooo
oooo
oooo

oooo
oooo
oooo
oooo

xoox
oooo
oooo
oooo

oxoo
oooo
oooo
oooo

ooxo
oooo
oooo
oooo

xooo
oooo
oooo
oooo

ooox
oooo
oooo
oooo

oooo
oooo
oooo
oooo

oooo
oooo
oooo
oooo

oxxo
oooo
oooo
oooo

xooo
oooo
oooo
oooo

oooo
oooo
oooo
oooo

xooo
oooo
oooo
oooo

oooo
oooo
oooo
oooo

xoox
oooo
oooo
oooo

oooo
oooo
oooo
oooo

oxxo
oooo
oooo
oooo

xooo
oooo
oooo
oooo

oooo
oooo
oooo
oooo

ooox
oooo
oooo
oooo

oooo
oooo
oooo
oooo

xooo
oooo
oooo
oooo

oooo
oooo
oooo
oooo

ooox
oooo
oooo
oooo

oooo
oooo
oooo
oooo

oxxo
oooo
oooo
oooo

oooo
oooo
oooo
oooo

xoox
oooo
oooo
oooo

oooo
oooo
oooo
oooo

xooo
oooo
oooo
oooo

oooo
oooo
oooo
oooo

ooox
oooo
oooo
oooo

oooo
oooo
oooo
oooo

xooo
oooo
oooo
oooo

oooo
oooo
oooo
oooo

xoox
oooo
oooo
oooo

oooo
oooo
oooo
oooo

xooo
oooo
oooo
oooo

oooo
oooo
oooo
oooo

xoox
oooo
oooo
oooo

oooo
oooo
oooo
oooo

oxxo
oooo
oooo
oooo

oooo
oooo
oooo
oooo

xoox
oooo
oooo
oooo

oooo
oooo
oooo
oooo

xoox
oooo
oooo
oooo

oxoo
oooo
oooo
oooo

ooxo
oooo
oooo
oooo

xooo
oooo
oooo
oooo

ooox
oooo
oooo
oooo

oooo
oooo
oooo
oooo

oooo
oooo
oooo
oooo

oxxo
oooo
oooo
oooo

xooo
oooo
oooo
oooo

oooo
oooo
oooo
oooo

xooo
oooo
oooo
oooo

oooo
oooo
oooo
oooo

xoox
oooo
oooo
oooo

oooo
oooo
oooo
oooo

oxxo
oooo
oooo
oooo

xooo
oooo
oooo
oooo

oooo
oooo
oooo
oooo

ooox
oooo
oooo
oooo

oooo
oooo
oooo
oooo

xooo
oooo
oooo
oooo

oooo
oooo
oooo
oooo

ooox
oooo
oooo
oooo

oooo
oooo
oooo
oooo

oxxo
oooo
oooo
oooo

oooo
oooo
oooo
oooo

xoox
oooo
oooo
oooo

oooo
oooo
oooo
oooo

xooo
oooo
oooo
oooo

oooo
oooo
oooo
oooo

ooox
oooo
oooo
oooo

oooo
oooo
oooo
oooo

xooo
oooo
oooo
oooo

oooo
oooo
oooo
oooo

xoox
oooo
oooo
oooo

oooo
oooo
oooo
oooo

xooo
oooo
oooo
oooo

oooo
oooo
oooo
oooo

xoox
oooo
oooo
oooo

oooo
oooo
oooo
oooo

oxxo
oooo
oooo
oooo

oooo
oooo
oooo
oooo

xoox
oooo
oooo
oooo

oooo
oooo
oooo
oooo

xoox
oooo
oooo
oooo

oxoo
oooo
oooo
oooo

ooxo
oooo
oooo
oooo

xooo
oooo
oooo
oooo

ooox
oooo
oooo
oooo

oooo
oooo
oooo
oooo

oooo
oooo
oooo
oooo

oxxo
oooo
oooo
oooo

xooo
oooo
oooo
oooo

oooo
oooo
oooo
oooo

xooo
oooo
oooo
oooo

oooo
oooo
oooo
oooo

xoox
oooo
oooo
oooo

oooo
oooo
oooo
oooo

oxxo
oooo
oooo
oooo

xooo
oooo
oooo
oooo

oooo
oooo
oooo
oooo

ooox
oooo
oooo
oooo

oooo
oooo
oooo
oooo

xooo
oooo
oooo
oooo

oooo
oooo
oooo
oooo

ooox
oooo
oooo
oooo

oooo
oooo
oooo
oooo

oxxo
oooo
oooo
oooo

oooo
oooo
oooo
oooo

xoox
oooo
oooo
oooo

oooo
oooo
oooo
oooo

xooo
oooo
oooo
oooo

oooo
oooo
oooo
oooo

ooox
oooo
oooo
oooo

oooo
oooo
oooo
oooo

xooo
oooo
oooo
oooo

oooo
oooo
oooo
oooo

xoox
oooo
oooo
oooo

oooo
oooo
oooo
oooo

xooo
oooo
oooo
oooo

oooo
oooo
oooo
oooo

xoox
oooo
oooo
oooo

oooo
oooo
oooo
oooo

oxxo
oooo
oooo
oooo

oooo
oooo
oooo
oooo

xoox
oooo
oooo
oooo

oooo
oooo
oooo
oooo

xoox
oooo
oooo
oooo

oxoo
oooo
oooo
oooo

ooxo
oooo
oooo
oooo

xooo
oooo
oooo
oooo

ooox
oooo
oooo
oooo

oooo
oooo
oooo
oooo

oooo
oooo
oooo
oooo

oxxo
oooo
oooo
oooo

xooo
oooo
oooo
oooo

oooo
oooo
oooo
oooo

xooo
oooo
oooo
oooo

oooo
oooo
oooo
oooo

xoox
oooo
oooo
oooo

oooo
oooo
oooo
oooo

oxxo
oooo
oooo
oooo