name: Build and Test
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    build-and-test:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
            fail-fast: false
        steps:
            - name: Install Linux Dependencies
              if: runner.os == 'Linux'
              run: sudo apt-get update && sudo apt-get install libxrandr-dev libxcursor-dev libxi-dev libudev-dev libflac-dev libvorbis-dev libgl1-mesa-dev libegl1-mesa-dev libfreetype-dev
      
            - uses: actions/checkout@v4
              with:
                ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Setup SSH
              uses: webfactory/ssh-agent@v0.7.0
              with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Configure CMake
              run: cmake -B build -DCMAKE_BUILD_TYPE=Release
                  
            - name: Build
              run: cmake --build build --config Release --parallel
                  
            - name: Run tests
              run: ctest --test-dir build --output-on-failure